[package]
name = "oxide-convergence"
version = "0.0.2"
edition = "2021"

[dependencies]
chrono = "0.4.38"
csv = "1.3.0"
format_num = "0.1.0"
getopts = "0.2.21"
num-format = "0.4.4"
rand = "0.10.0"
rayon = "1.10.0"
regex = "1.10.4"
statrs = "0.18.0"
